patients = {
    '1': {
        'id': 1,
        'name': 'Patient_1',
        'gender': 'male',
        'doctor_name': 'Doctor_1',
        'ward': 1,
        'bunk': 1,
        'date_in': '20/03/2020',
    },
    '2': {
        'id': 2,
        'name': 'Patient_2',
        'gender': 'female',
        'doctor_name': 'Doctor_1',
        'ward': 1,
        'bunk': 2,
        'date_in': '30/03/2020',
    },
    '3': {
        'id': 3,
        'name': 'Patient_3',
        'gender': 'male',
        'doctor_name': 'Doctor_1',
        'ward': 1,
        'bunk': 3,
        'date_in': '10/04/2020',
    },
    '4': {
        'id': 4,
        'name': 'Patient_4',
        'gender': 'female',
        'doctor_name': 'Doctor_4',
        'ward': 2,
        'bunk': 4,
        'date_in': '20/04/2020',
    },
    '5': {
        'id': 5,
        'name': 'Patient_5',
        'gender': 'male',
        'doctor_name': 'Doctor_1',
        'ward': 2,
        'bunk': 5,
        'date_in': '30/04/2020',
    },
    '6': {
        'id': 6,
        'name': 'Patient_6',
        'gender': 'female',
        'doctor_name': 'Doctor_1',
        'ward': 2,
        'bunk': 6,
        'date_in': '10/05/2020',
    }
}
